name: Run Tests On Push

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.15
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.15
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          echo "Requirements installed"
      - name: Run tests
        env:
          SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd tests
          pip install pytest
          pytest

